# -*- coding: utf-8 -*-
"""project oceanscore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzdj2cA96EmV-BkINeQ4OD_-U0ioDg3Z

shaun project
"""

!pip -q install xarray netCDF4 pydap statsmodels scikit-learn requests

# ============================================================
# CELL 1 — Pull CCE2 data straight from THREDDS via OPeNDAP
# ============================================================
import xarray as xr, numpy as np, pandas as pd

BASE = "https://dods.ndbc.noaa.gov/thredds/dodsC/oceansites/DATA/CCE2"
DEPLOY = "17"   # current deployment as of April 2026

FILES = {
    "ph":   f"{BASE}/OS_CCE2_{DEPLOY}_P_PH-15m.nc",
    "do":   f"{BASE}/OS_CCE2_{DEPLOY}_D_OXYGEN.nc",
    "chl":  f"{BASE}/OS_CCE2_{DEPLOY}_D_CHL.nc",
    "no3":  f"{BASE}/OS_CCE2_{DEPLOY}_D_NO3.nc",
    "ctd":  f"{BASE}/OS_CCE2_{DEPLOY}_D_CTD.nc",
}

def load(url):
    ds = xr.open_dataset(url, engine="netcdf4")
    print(url.split("/")[-1], "→ vars:", list(ds.data_vars))
    return ds

dsets = {k: load(u) for k, u in FILES.items()}
# Inspect once and pick the right variable names — OceanSITES uses CF
# standard names like PH, DOXY, CPHL, NTRA, TEMP, PSAL. Print confirms.

# ============================================================
# CELL 2 — Build a unified hourly DataFrame of stress variables
# ============================================================
def to_series(ds, var, name):
    # Many OceanSITES files have (TIME, DEPTH); take shallowest depth
    da = ds[var]
    if "DEPTH" in da.dims:
        da = da.isel(DEPTH=0)
    s = da.to_series().rename(name)
    s.index = pd.to_datetime(s.index)
    return s.dropna()

ph  = to_series(dsets["ph"],  "PH_TOT", "ph")
do  = to_series(dsets["do"],  "DOX2",   "do")
chl = to_series(dsets["chl"], "CHL",    "chl")
no3 = to_series(dsets["no3"], "NO3",    "no3")

df = pd.concat([ph, do, chl, no3], axis=1)
df = df.resample("1H").mean().interpolate(limit=6)  # fill <6h gaps
df = df.dropna()
print(df.tail(), "\nshape:", df.shape)

# ============================================================
# CELL 3 — STL seasonal decomposition → residuals per variable
# ============================================================
from statsmodels.tsa.seasonal import STL

# CELL 3 — shorter period
def deseasonalize(series, period_hours=24*7):  # weekly cycle, not monthly
    stl = STL(series, period=period_hours, robust=True).fit()
    return series - stl.seasonal - stl.trend

resid = pd.DataFrame({c: deseasonalize(df[c]) for c in df.columns})
resid = resid.dropna()

# ============================================================
# CELL 4 — Isolation Forest → daily Ocean Stress Index 0–2
# ============================================================
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler

X = RobustScaler().fit_transform(resid.values)

# Fit on first 70% (train), score the rest (test)
n = len(X); split = int(0.7*n)
iso = IsolationForest(contamination=0.1, random_state=42).fit(X[:split])

# score_samples: higher = more normal. Flip + rescale to 0–2.
raw = -iso.score_samples(X)
lo, hi = np.quantile(raw[:split], [0.05, 0.95])
stress = np.clip(2 * (raw - lo) / (hi - lo), 0, 2)
stress_series = pd.Series(stress, index=resid.index, name="stress")

current_stress = float(stress_series.iloc[-24*7:].mean())
print(f"Current Ocean Stress Index: {current_stress:.2f}  (1.0 = normal)")

# ============================================================
# CELL 5 — Evaluation
# ============================================================
from sklearn.metrics import precision_recall_fscore_support
from scipy.stats import spearmanr

# (a) Forecast accuracy: 1-step persistence baseline vs STL+trend
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error
for c in df.columns:
    s = df[c].dropna()
    stl = STL(s, period=24*30, robust=True).fit()
    pred = (stl.trend + stl.seasonal).iloc[split:]
    true = s.iloc[split:]
    rmse = root_mean_squared_error(true, pred)
    mae  = mean_absolute_error(true, pred)
    print(f"{c:6s}  RMSE={rmse:.3f}  MAE={mae:.3f}")

# (b) Synthetic anomaly injection on test set
rng = np.random.default_rng(0)
X_test = X[split:].copy()
n_test = len(X_test)
inject_idx = rng.choice(n_test, size=n_test//20, replace=False)
X_test[inject_idx] += rng.normal(4, 1, size=(len(inject_idx), X.shape[1]))

scores = -iso.score_samples(X_test)
threshold = np.quantile(-iso.score_samples(X[:split]), 0.9)
pred_anom = scores > threshold
true_anom = np.zeros(n_test, bool); true_anom[inject_idx] = True
p, r, f, _ = precision_recall_fscore_support(true_anom, pred_anom, average="binary")
print(f"\nSynthetic injection — Precision={p:.2f} Recall={r:.2f} F1={f:.2f}")

# (c) Sanity plot
import matplotlib.pyplot as plt
stress_series.resample("1D").mean().plot(figsize=(10,3),
    title="Ocean Stress Index over CCE2-17 deployment")
plt.axhline(1.0, color="k", ls="--", alpha=0.5); plt.show()

# ============================================================
# CELL 6 — Wire into OceanScore
# ============================================================
IMPACTS = {
  "beef":     {"co2":99.5,"runoff":0.95,"plastic":0.3,"water":15400},
  "poultry":  {"co2":9.9, "runoff":0.55,"plastic":0.4,"water":4300},
  "legume":   {"co2":0.9, "runoff":0.15,"plastic":0.2,"water":4055},
  "vegetable":{"co2":2.0, "runoff":0.25,"plastic":0.4,"water":322},
  "fish":     {"co2":13.6,"runoff":0.25,"plastic":0.6,"water":3700},
  "dairy":    {"co2":9.8, "runoff":0.80,"plastic":0.5,"water":1020},
  "fruit":    {"co2":1.1, "runoff":0.20,"plastic":0.4,"water":962},
  "processed":{"co2":5.0, "runoff":0.40,"plastic":0.8,"water":2000},

}

WORST = {"co2":30, "runoff":0.6, "plastic":0.6, "water":5000}

def ocean_score(category, stress_idx=current_stress):
    f = IMPACTS.get(category, IMPACTS["vegetable"])
    co2     = 1 - min(f["co2"]/WORST["co2"], 1)
    runoff  = 1 - min((f["runoff"]*stress_idx)/(WORST["runoff"]*1.5), 1)
    plastic = 1 - f["plastic"]
    water   = 1 - min(f["water"]/WORST["water"], 1)
    return round(100*(0.35*co2 + 0.30*runoff + 0.20*plastic + 0.15*water))

import requests

HEADERS = {"User-Agent": "OceanScore/0.1 (datahacks2026)"}

def barcode_to_score(barcode):
    url = f"https://world.openfoodfacts.org/api/v2/product/{barcode}.json"
    r = requests.get(url, headers=HEADERS, timeout=10)
    if r.status_code != 200:
        return {"error": f"HTTP {r.status_code}"}
    try:
        data = r.json()
    except ValueError:
        return {"error": "non-JSON response", "body": r.text[:200]}
    if data.get("status") != 1:
        return {"error": "product not found", "barcode": barcode}
    p = data["product"]
    cats = p.get("categories_tags") or []
    cat_map = {
        "beef":"beef", "chicken":"poultry", "poultry":"poultry",
        "fish":"fish", "seafood":"fish", "dairy":"dairy",
        "legumes":"legume", "vegetables":"vegetable", "fruits":"fruit",
        "chocolate":"processed", "spreads":"processed",
        "sugary-snacks":"processed", "snacks":"processed",
        "sodas":"processed", "beverages":"processed",
    }
    category = next((v for k,v in cat_map.items() if any(k in c for c in cats)), "processed")
    return {"name": p.get("product_name"), "category": category,
            "score": ocean_score(category), "stress_idx": current_stress}

print(barcode_to_score("3017620422003"))  # Nutella

# ============================================================
# CELL 7 — Validate OceanScore against OpenFoodFacts Eco-Score
# ============================================================
import requests, time
from scipy.stats import spearmanr
import pandas as pd

# 50 real barcodes across categories — meat, dairy, processed, produce, etc.
BARCODES = [
    "3017620422003",  # Nutella
    "5449000000996",  # Coca-Cola
    "8076809513753",  # Barilla pasta
    "3175680011480",  # canned green beans
    "0028400090315",  # Doritos
    "0038000138416",  # Cheerios
    "7622210449283",  # Oreo
    "3046920022606",  # Lindt chocolate
    "4006381333641",  # Stabilo (won't have ecoscore — filtered)
    "8000500310427",  # Ferrero Rocher
    "3033710065967",  # President butter
    "3608580736912",  # Yoplait yogurt
    "3270190022114",  # Evian water
    "3245412567216",  # bread
    "3560070048786",  # Carrefour rice
    "8001505005707",  # San Pellegrino
    "5000159407236",  # Snickers
    "3329770063648",  # apples
    "20724696",       # bananas
    "3068320115008",  # Volvic
    "3033491510014",  # baguette
    "3257980031000",  # tuna can
    "3270160830053",  # cornflakes
    "8480000823779",  # olive oil
    "5000168190631",  # tea bags
    "3661112004143",  # ground beef
    "8410076472199",  # chickpeas
    "3038359005114",  # lentils
    "3168930010265",  # camembert
    "3023290260166",  # ham
    "5411188119098",  # Belgian beer
    "8000430112856",  # Mulino Bianco
    "5057967388912",  # Tesco milk
    "3245391225114",  # Carrefour eggs
    "8410128710262",  # Iberico ham
    "3700214612385",  # frozen pizza
    "3596710443307",  # frozen peas
    "3175681810044",  # canned tomatoes
    "8002270014901",  # Lavazza coffee
    "3023470001015",  # Roquefort
    "3033491610011",  # croissant
    "3560070976478",  # orange juice
    "3017800238400",  # Bonduelle corn
    "3242272379354",  # apple juice
    "8717377001135",  # Heinz ketchup
    "5410188006438",  # Alpro soy milk
    "3596710401352",  # frozen salmon
    "8000380025114",  # Mutti tomato sauce
    "3017620425035",  # Kinder Bueno
    "3245412365119",  # baguette
]

HEADERS = {"User-Agent": "OceanScore/0.1 (datahacks2026)"}

def fetch_product(barcode):
    try:
        r = requests.get(
            f"https://world.openfoodfacts.org/api/v2/product/{barcode}.json",
            headers=HEADERS, timeout=10
        )
        if r.status_code != 200: return None
        d = r.json()
        if d.get("status") != 1: return None
        p = d["product"]
        eco = p.get("ecoscore_score")
        if eco is None: return None  # skip products without an ecoscore
        cats = p.get("categories_tags") or []
        cat_map = {
            "beef":"beef", "chicken":"poultry", "poultry":"poultry",
            "fish":"fish", "seafood":"fish", "dairy":"dairy",
            "legumes":"legume", "vegetables":"vegetable", "fruits":"fruit",
            "chocolate":"processed", "spreads":"processed",
            "sugary-snacks":"processed", "snacks":"processed",
            "sodas":"processed", "beverages":"processed",
        }
        category = next((v for k,v in cat_map.items() if any(k in c for c in cats)), "processed")
        return {
            "barcode": barcode,
            "name": p.get("product_name","")[:30],
            "category": category,
            "ecoscore": eco,
            "oceanscore": ocean_score(category),
        }
    except Exception as e:
        return None

rows = []
for b in BARCODES:
    row = fetch_product(b)
    if row: rows.append(row)
    time.sleep(0.1)  # be nice to the API

results = pd.DataFrame(rows)
print(f"Got {len(results)} products with both scores\n")
print(results.to_string(index=False))

rho, pval = spearmanr(results["ecoscore"], results["oceanscore"])
print(f"\nSpearman ρ = {rho:.3f}   (p = {pval:.4f})")
print("Interpretation: >0.6 = good, 0.3–0.6 = okay, <0.3 = weights are wrong")

# ============================================================
# CELL 8 — FINAL DASHBOARD (Agribalyse + LLM fallback + ML stress)
# ============================================================
import matplotlib.pyplot as plt
import pandas as pd, requests, time, os, json
from scipy.stats import spearmanr
from statsmodels.tsa.seasonal import STL
from sklearn.metrics import root_mean_squared_error, mean_absolute_error
import anthropic

# Make sure ANTHROPIC_API_KEY is set above this cell:
# os.environ["ANTHROPIC_API_KEY"] = "sk-ant-..."
client = anthropic.Anthropic()

print("="*60)
print(" PROJECT OCEANSCORE — FINAL RESULTS")
print(" Datahacks 2026 · Scripps Challenge")
print("="*60)

IMPACTS["pork"]  = {"co2":12.3,"runoff":0.70,"plastic":0.4,"water":6000}
IMPACTS["eggs"]  = {"co2":4.7, "runoff":0.45,"plastic":0.4,"water":3300}
IMPACTS["grain"] = {"co2":2.7, "runoff":0.35,"plastic":0.3,"water":1600}
IMPACTS["nuts"]  = {"co2":2.3, "runoff":0.10,"plastic":0.3,"water":9060}

HEADERS = {"User-Agent":"OceanScore/0.1 (datahacks2026)"}
DEEP = "code,product_name,categories_tags,ecoscore_score,ecoscore_data,packagings,image_front_url"

# ---- LLM fallback for products without Agribalyse data ----
def llm_estimate(product_name, image_url=None):
    prompt = f"""Estimate environmental impact for this food product: "{product_name}"

Return ONLY a JSON object, no markdown, no code fences, no commentary:
{{
  "co2_total_kg": <float, kg CO2-eq per kg product, typical 0.5-50>,
  "ef_total": <float, environmental footprint score 0.0-1.5, includes eutrophication>,
  "has_plastic_packaging": <true/false>,
  "estimated_ecoscore": <int 0-100, environmental friendliness, 100=best>
}}"""
    content = [{"type": "text", "text": prompt}]
    if image_url:
        content.insert(0, {"type": "image",
                           "source": {"type": "url", "url": image_url}})
    msg = client.messages.create(
        model="claude-haiku-4-5",
        max_tokens=300,
        messages=[{"role": "user", "content": content}],
    )
    txt = msg.content[0].text.strip()
    if txt.startswith("```"):
        txt = txt.split("```")[1]
        if txt.startswith("json"): txt = txt[4:]
        txt = txt.strip()
    return json.loads(txt)

# ---- Per-product scoring (Agribalyse → LLM fallback) ----
def score_real(barcode):
    try:
        r = requests.get(f"https://world.openfoodfacts.org/api/v2/product/{barcode}.json",
                         headers=HEADERS, params={"fields": DEEP}, timeout=10)
        d = r.json()
        if d.get("status") != 1: return None
        p = d["product"]
        agb = (p.get("ecoscore_data") or {}).get("agribalyse") or {}
        pkgs = p.get("packagings") or []
        plastic = any("plastic" in (pk.get("material") or "").lower()
                      or "pet" in (pk.get("material") or "").lower() for pk in pkgs)
        llm_eco = None

        if agb.get("co2_total") is not None:
            co2_kg = agb["co2_total"]
            ef     = agb.get("ef_total") or 0.5
            source = "agribalyse"
            eco    = p.get("ecoscore_score")
        else:
            est = llm_estimate(p.get("product_name","unknown"),
                               image_url=p.get("image_front_url"))
            co2_kg  = est["co2_total_kg"]
            ef      = est["ef_total"]
            plastic = plastic or est["has_plastic_packaging"]
            source  = "llm"
            eco     = est.get("estimated_ecoscore")

        co2     = 1 - min(co2_kg/30.0, 1)
        ef_norm = 1 - min(ef/1.0, 1)
        runoff  = ef_norm * (2 - current_stress) / 2
        plastic_term = 0.3 if plastic else 1.0
        score = round(100*(0.30*co2 + 0.30*runoff + 0.20*plastic_term + 0.20*ef_norm))

        return {"name": p.get("product_name","?")[:25], "source": source,
                "co2": round(co2_kg,1), "ef": round(ef,2),
                "plastic": "Y" if plastic else "N",
                "OceanScore": score, "off_eco": eco}
    except Exception as e:
        print(f"  ! {barcode}: {e}")
        return None

# ---- 1. ML stress index ----
print(f"\n[1] OCEAN STRESS INDEX (CCE2-17)")
print(f"    Current (last 7d): {current_stress:.2f}   Mean: {stress_series.mean():.2f}   "
      f"Range: [{stress_series.min():.2f}, {stress_series.max():.2f}]")
print(f"    0=calm · 1=normal · 2=highly stressed")

# ---- 2. Score 10 real products ----
print("\n[2] OCEANSCORE — 10 REAL PRODUCTS (per-SKU data)")
DEMO_BARCODES = [
    ("Nutella",         "3017620422003"),
    ("Coca-Cola",       "5449000000996"),
    ("Heinz ketchup",   "8717377001135"),
    ("Lindt chocolate", "3046920022606"),
    ("Barilla pasta",   "8076809513753"),
    ("Alpro soy milk",  "5410188006438"),
    ("Olive oil",       "8480000823779"),
    ("Tomato sauce",    "8000380025114"),
    ("Mineral water",   "3068320115008"),
    ("Lavazza coffee",  "8002270014901"),
]
rows = []
for name, bc in DEMO_BARCODES:
    s = score_real(bc)
    if s: rows.append({"product": name, **s})
    time.sleep(0.1)
demo_df = pd.DataFrame(rows).sort_values("OceanScore", ascending=True)
print(demo_df[["product","co2","ef","plastic","OceanScore","source"]].to_string(index=False))

# ---- 3. What-if swap ----
print("\n[3] WHAT-IF SWAP")
worst = demo_df.iloc[0]; best = demo_df.iloc[-1]
print(f"    Swap '{worst['product']}' (score {worst['OceanScore']})")
print(f"    → for '{best['product']}'  (+{best['OceanScore']-worst['OceanScore']} points)")

# ---- 4. Evaluation ----
print("\n[4] EVALUATION")
print("    (a) Stress-model forecast error:")
for c in df.columns:
    s = df[c].dropna(); split_local = int(0.7*len(s))
    stl = STL(s, period=24*7, robust=True).fit()
    pred = (stl.trend + stl.seasonal).iloc[split_local:]; true = s.iloc[split_local:]
    print(f"        {c:5s}  RMSE={root_mean_squared_error(true,pred):.3f}  "
          f"MAE={mean_absolute_error(true,pred):.3f}")

valid = demo_df.dropna(subset=["off_eco"])
if len(valid) >= 3:
    rho, pval = spearmanr(valid["off_eco"], valid["OceanScore"])
    verdict = "STRONG ✅" if rho > 0.6 else "OKAY ⚠️" if rho > 0.3 else "WEAK ❌"
    print(f"\n    (b) Spearman ρ vs Eco-Score: {rho:.3f} (n={len(valid)})  {verdict}")
else:
    rho = None

# ---- 5. Dashboard ----
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

stress_series.resample("1D").mean().plot(ax=axes[0], color="steelblue")
axes[0].axhline(1.0, color="k", ls="--", alpha=0.4, label="normal")
axes[0].set_title("Ocean Stress Index — CCE2-17")
axes[0].set_ylabel("stress (0=calm, 2=stressed)"); axes[0].legend()

colors = ["#2ecc71" if s>=70 else "#f39c12" if s>=40 else "#e74c3c"
          for s in demo_df["OceanScore"]]
axes[1].barh(demo_df["product"], demo_df["OceanScore"], color=colors)
axes[1].set_xlim(0,100); axes[1].set_title("OceanScore — real products")
axes[1].set_xlabel("score (0=worst, 100=best)")

if rho is not None:
    axes[2].scatter(valid["off_eco"], valid["OceanScore"], alpha=0.7, color="teal", s=80)
    axes[2].plot([0,100],[0,100], "k--", alpha=0.3)
    axes[2].set_xlabel("Eco-Score (Agribalyse + LLM)"); axes[2].set_ylabel("OceanScore")
    axes[2].set_title(f"Validation (ρ={rho:.2f}, n={len(valid)})")
else:
    axes[2].text(0.5,0.5,"Not enough\nproducts with\nEco-Score", ha="center",
                 va="center", transform=axes[2].transAxes)

plt.tight_layout(); plt.show()
print("\n" + "="*60)
print(" END — ready for app integration")
print("="*60)

# ============================================================
# CELL 9 — Image scan → barcode → OceanScore
# ============================================================
!apt-get install -y libzbar0 -qq
!pip -q install pyzbar pillow

from pyzbar.pyzbar import decode
from PIL import Image, ImageEnhance
import numpy as np
import base64

def image_to_barcode(image_path):
    """Extract barcode number(s) from a product photo. Returns list of strings."""
    img = Image.open(image_path)

    # Pass 1: raw image
    results = decode(img)
    if results:
        return [r.data.decode("utf-8") for r in results]

    # Pass 2: grayscale + contrast boost (helps with blurry/dim photos)
    img_gray = img.convert("L")
    img_boost = ImageEnhance.Contrast(img_gray).enhance(2.0)
    results = decode(img_boost)
    if results:
        return [r.data.decode("utf-8") for r in results]

    # Pass 3: try a few rotations (handles tilted phone photos)
    for angle in [90, 180, 270]:
        results = decode(img.rotate(angle, expand=True))
        if results:
            return [r.data.decode("utf-8") for r in results]

    # Pass 4: LLM vision fallback (uses your existing client from Cell 8)
    try:
        with open(image_path, "rb") as f:
            b64 = base64.standard_b64encode(f.read()).decode()
        msg = client.messages.create(
            model="claude-haiku-4-5", max_tokens=50,
            messages=[{"role":"user","content":[
                {"type":"image","source":{"type":"base64",
                    "media_type":"image/jpeg","data":b64}},
                {"type":"text","text":"Read the barcode number on this product. Return ONLY the digits, nothing else. If no barcode is visible, return 'NONE'."}
            ]}]
        )
        bc = msg.content[0].text.strip()
        return [bc] if bc != "NONE" and bc.isdigit() else []
    except Exception:
        return []

def scan_and_score(image_path):
    """End-to-end: photo → barcode → OceanScore (uses score_real from Cell 8)."""
    barcodes = image_to_barcode(image_path)
    if not barcodes:
        return {"error": "no barcode detected — try a clearer photo"}
    bc = barcodes[0]
    print(f"📷 Detected barcode: {bc}")
    result = score_real(bc)
    if result:
        print(f"🌊 {result['name']}: OceanScore {result['OceanScore']} ({result['source']})")
    return result

# ---- Demo: upload a product photo ----
from google.colab import files
print("Upload a photo of a product or barcode:")
uploaded = files.upload()
for fname in uploaded:
    print(f"\n--- {fname} ---")
    print(scan_and_score(fname))

#result = scan_and_score("/path/to/uploaded.jpg")
#Test it now: take a phone photo of any product barcode, upload, and you should see the full pipeline run end-to-end — image → digits → product info → OceanScore.