# -*- coding: utf-8 -*-
"""project oceanscore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzdj2cA96EmV-BkINeQ4OD_-U0ioDg3Z
"""

"""
scan_label.py — Aarav's food label scanner (backend/classification)

Takes an image of a food label and returns a FoodItem with impact fields
ready for ocean scoring. Uses Claude vision to extract product details,
then maps to category-level impact values from the shared lookup table.

Usage:
    python scan_label.py path/to/label.jpg
    or import scan_label and call scan_label_image(image_path)
"""

import base64
import json
import sys
from dataclasses import dataclass, asdict
from pathlib import Path

import anthropic

# ── Shared category list (agreed with Sean) ─────────────────────────────────
VALID_CATEGORIES = [
    "beef",
    "dairy",
    "poultry",
    "seafood",
    "vegetables",
    "fruit",
    "legumes",
    "grains",
    "packaged snacks",
    "beverages",
    "household",
    "unknown",
]

# ── Baseline impact table (0-100 penalty scale, higher = worse) ──────────────
# These values feed directly into the ocean score formula:
#   raw_penalty = 0.4*climate_impact + 0.4*runoff_impact*stress_mult + 0.2*plastic_impact
#   ocean_score = max(0, 100 - raw_penalty)
CATEGORY_IMPACTS: dict[str, dict[str, int]] = {
    "beef":            {"climate_impact": 92, "runoff_impact": 85, "plastic_impact": 20},
    "dairy":           {"climate_impact": 65, "runoff_impact": 70, "plastic_impact": 40},
    "poultry":         {"climate_impact": 45, "runoff_impact": 50, "plastic_impact": 30},
    "seafood":         {"climate_impact": 30, "runoff_impact": 20, "plastic_impact": 50},
    "vegetables":      {"climate_impact": 15, "runoff_impact": 35, "plastic_impact": 25},
    "fruit":           {"climate_impact": 18, "runoff_impact": 30, "plastic_impact": 30},
    "legumes":         {"climate_impact": 10, "runoff_impact": 20, "plastic_impact": 20},
    "grains":          {"climate_impact": 20, "runoff_impact": 25, "plastic_impact": 15},
    "packaged snacks": {"climate_impact": 40, "runoff_impact": 30, "plastic_impact": 75},
    "beverages":       {"climate_impact": 25, "runoff_impact": 20, "plastic_impact": 80},
    "household":       {"climate_impact": 35, "runoff_impact": 60, "plastic_impact": 85},
    "unknown":         {"climate_impact": 50, "runoff_impact": 50, "plastic_impact": 50},
}

# Organic certification lowers runoff_impact (less synthetic fertilizer/pesticide runoff)
ORGANIC_RUNOFF_REDUCTION = 15

# Local/regional sourcing lowers climate_impact (shorter transport chain)
LOCAL_CLIMATE_REDUCTION = 10


@dataclass
class FoodItem:
    # ── From label extraction ────────────────────────────────────────────────
    normalized_name: str          # e.g. "organic whole milk"
    brand: str                    # e.g. "Horizon"
    category: str                 # one of VALID_CATEGORIES
    classification_confidence: float  # 0.0–1.0

    # Label-derived signals that modulate impact
    is_organic: bool              # USDA Organic or equivalent on label
    is_local: bool                # "local", "regional", state/county claim
    packaging_type: str           # "plastic", "cardboard", "glass", "can", "mixed", "unknown"
    key_ingredients: list[str]    # top 3–5 ingredients from label

    # ── Derived impact scores (0–100 penalty, higher = worse) ───────────────
    # These are the values the ML scoring layer will consume.
    climate_impact: int
    runoff_impact: int
    plastic_impact: int

    # Optional raw scan metadata for Sean's pipeline traceability
    raw_label_text: str = ""      # any text Claude pulled verbatim from the label


def _encode_image(image_path: str) -> tuple[str, str]:
    """Return (base64_data, media_type) for a local image file."""
    path = Path(image_path)
    suffix = path.suffix.lower()
    media_map = {
        ".jpg":  "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png":  "image/png",
        ".gif":  "image/gif",
        ".webp": "image/webp",
    }
    media_type = media_map.get(suffix, "image/jpeg")
    with open(path, "rb") as f:
        data = base64.standard_b64encode(f.read()).decode("utf-8")
    return data, media_type


def _extract_label_info(client: anthropic.Anthropic, image_path: str) -> dict:
    """
    Send the label image to Claude vision and get back structured JSON
    describing the product.
    """
    img_data, media_type = _encode_image(image_path)

    system_prompt = (
        "You are a food label analysis assistant for an ocean health app. "
        "Extract product information from the label image and return ONLY valid JSON "
        "with no markdown or extra text."
    )

    user_prompt = f"""Analyze this food label image and return a JSON object with exactly these fields:

{{
  "normalized_name": "lowercase descriptive product name (e.g. 'organic whole milk', 'ground beef 80/20')",
  "brand": "brand or manufacturer name, empty string if not visible",
  "category": "one of: {', '.join(VALID_CATEGORIES)}",
  "classification_confidence": 0.0 to 1.0 float representing how certain you are of the category,
  "is_organic": true or false (true only if label explicitly claims USDA Organic or certified organic),
  "is_local": true or false (true if label says local, regional, or names a specific nearby state/county),
  "packaging_type": "one of: plastic, cardboard, glass, can, mixed, unknown",
  "key_ingredients": ["top 3 to 5 ingredients from the ingredients list"],
  "raw_label_text": "any brand name, product name, or certifications you can read verbatim"
}}

Be conservative with classification_confidence — use values below 0.7 if the label is unclear or the category is ambiguous."""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        system=system_prompt,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": img_data,
                        },
                    },
                    {"type": "text", "text": user_prompt},
                ],
            }
        ],
    )

    raw = response.content[0].text.strip()
    # Strip markdown code fences if Claude wraps in them
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    return json.loads(raw)


def _apply_impact_modifiers(
    impacts: dict[str, int],
    is_organic: bool,
    is_local: bool,
    packaging_type: str,
) -> tuple[int, int, int]:
    """
    Apply label-derived modifiers to the baseline category impacts.
    Returns (climate_impact, runoff_impact, plastic_impact).
    """
    climate = impacts["climate_impact"]
    runoff  = impacts["runoff_impact"]
    plastic = impacts["plastic_impact"]

    if is_organic:
        runoff = max(0, runoff - ORGANIC_RUNOFF_REDUCTION)

    if is_local:
        climate = max(0, climate - LOCAL_CLIMATE_REDUCTION)

    # Packaging type nudges plastic_impact
    packaging_adjustments = {
        "plastic":   +10,
        "glass":     -15,
        "cardboard": -10,
        "can":       -5,
        "mixed":     +5,
        "unknown":    0,
    }
    plastic = max(0, min(100, plastic + packaging_adjustments.get(packaging_type, 0)))

    return climate, runoff, plastic


def scan_label_image(image_path: str) -> FoodItem:
    """
    Main entry point. Given a path to a food label image, returns a FoodItem
    with all impact fields populated and ready for the ocean scoring pipeline.
    """
    client = anthropic.Anthropic()

    extracted = _extract_label_info(client, image_path)

    # Normalize category to the agreed list
    category = extracted.get("category", "unknown").lower().strip()
    if category not in VALID_CATEGORIES:
        category = "unknown"

    base_impacts = CATEGORY_IMPACTS[category]

    is_organic = bool(extracted.get("is_organic", False))
    is_local   = bool(extracted.get("is_local", False))
    packaging  = extracted.get("packaging_type", "unknown").lower().strip()

    climate, runoff, plastic = _apply_impact_modifiers(
        base_impacts, is_organic, is_local, packaging
    )

    return FoodItem(
        normalized_name=extracted.get("normalized_name", "unknown product"),
        brand=extracted.get("brand", ""),
        category=category,
        classification_confidence=float(extracted.get("classification_confidence", 0.5)),
        is_organic=is_organic,
        is_local=is_local,
        packaging_type=packaging,
        key_ingredients=extracted.get("key_ingredients", []),
        climate_impact=climate,
        runoff_impact=runoff,
        plastic_impact=plastic,
        raw_label_text=extracted.get("raw_label_text", ""),
    )


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scan_label.py <path_to_label_image>")
        sys.exit(1)

    image_path = sys.argv[1]
    print(f"Scanning label: {image_path}\n")

    item = scan_label_image(image_path)
    print(json.dumps(asdict(item), indent=2))

# Example of how to call scan_label_image with a placeholder image path:
# First, upload an image file (e.g., 'my_food_label.jpg') to your Colab environment.
# Then, replace 'path/to/your/image.jpg' with the actual path to your uploaded image.

# from scan_label import scan_label_image # If this was a separate module, you'd import it.
# Since the functions are in the current cell, they are directly accessible.

# Example usage:
# image_file_path = "/content/my_food_label.jpg"  # Replace with your actual image path
# try:
#     food_item = scan_label_image(image_file_path)
#     print(json.dumps(asdict(food_item), indent=2))
# except FileNotFoundError:
#     print(f"Error: Image file not found at {image_file_path}. Please check the path.")
# except Exception as e:
#     print(f"An error occurred: {e}")

print("To scan a label, upload an image file (e.g., to /content/) and then uncomment and run the example code above with the correct path.")

!pip install anthropic

"""shaun project"""

!pip -q install xarray netCDF4 pydap statsmodels scikit-learn requests

# ============================================================
# CELL 1 — Pull CCE2 data straight from THREDDS via OPeNDAP
# ============================================================
import xarray as xr, numpy as np, pandas as pd

BASE = "https://dods.ndbc.noaa.gov/thredds/dodsC/oceansites/DATA/CCE2"
DEPLOY = "17"   # current deployment as of April 2026

FILES = {
    "ph":   f"{BASE}/OS_CCE2_{DEPLOY}_P_PH-15m.nc",
    "do":   f"{BASE}/OS_CCE2_{DEPLOY}_D_OXYGEN.nc",
    "chl":  f"{BASE}/OS_CCE2_{DEPLOY}_D_CHL.nc",
    "no3":  f"{BASE}/OS_CCE2_{DEPLOY}_D_NO3.nc",
    "ctd":  f"{BASE}/OS_CCE2_{DEPLOY}_D_CTD.nc",
}

def load(url):
    ds = xr.open_dataset(url, engine="netcdf4")
    print(url.split("/")[-1], "→ vars:", list(ds.data_vars))
    return ds

dsets = {k: load(u) for k, u in FILES.items()}
# Inspect once and pick the right variable names — OceanSITES uses CF
# standard names like PH, DOXY, CPHL, NTRA, TEMP, PSAL. Print confirms.

# ============================================================
# CELL 2 — Build a unified hourly DataFrame of stress variables
# ============================================================
def to_series(ds, var, name):
    # Many OceanSITES files have (TIME, DEPTH); take shallowest depth
    da = ds[var]
    if "DEPTH" in da.dims:
        da = da.isel(DEPTH=0)
    s = da.to_series().rename(name)
    s.index = pd.to_datetime(s.index)
    return s.dropna()

ph  = to_series(dsets["ph"],  "PH_TOT", "ph")
do  = to_series(dsets["do"],  "DOX2",   "do")
chl = to_series(dsets["chl"], "CHL",    "chl")
no3 = to_series(dsets["no3"], "NO3",    "no3")

df = pd.concat([ph, do, chl, no3], axis=1)
df = df.resample("1H").mean().interpolate(limit=6)  # fill <6h gaps
df = df.dropna()
print(df.tail(), "\nshape:", df.shape)

# ============================================================
# CELL 3 — STL seasonal decomposition → residuals per variable
# ============================================================
from statsmodels.tsa.seasonal import STL

# CELL 3 — shorter period
def deseasonalize(series, period_hours=24*7):  # weekly cycle, not monthly
    stl = STL(series, period=period_hours, robust=True).fit()
    return series - stl.seasonal - stl.trend

resid = pd.DataFrame({c: deseasonalize(df[c]) for c in df.columns})
resid = resid.dropna()

# ============================================================
# CELL 4 — Isolation Forest → daily Ocean Stress Index 0–2
# ============================================================
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler

X = RobustScaler().fit_transform(resid.values)

# Fit on first 70% (train), score the rest (test)
n = len(X); split = int(0.7*n)
iso = IsolationForest(contamination=0.1, random_state=42).fit(X[:split])

# score_samples: higher = more normal. Flip + rescale to 0–2.
raw = -iso.score_samples(X)
lo, hi = np.quantile(raw[:split], [0.05, 0.95])
stress = np.clip(2 * (raw - lo) / (hi - lo), 0, 2)
stress_series = pd.Series(stress, index=resid.index, name="stress")

current_stress = float(stress_series.iloc[-24*7:].mean())
print(f"Current Ocean Stress Index: {current_stress:.2f}  (1.0 = normal)")

# ============================================================
# CELL 5 — Evaluation
# ============================================================
from sklearn.metrics import precision_recall_fscore_support
from scipy.stats import spearmanr

# (a) Forecast accuracy: 1-step persistence baseline vs STL+trend
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error
for c in df.columns:
    s = df[c].dropna()
    stl = STL(s, period=24*30, robust=True).fit()
    pred = (stl.trend + stl.seasonal).iloc[split:]
    true = s.iloc[split:]
    rmse = root_mean_squared_error(true, pred)
    mae  = mean_absolute_error(true, pred)
    print(f"{c:6s}  RMSE={rmse:.3f}  MAE={mae:.3f}")

# (b) Synthetic anomaly injection on test set
rng = np.random.default_rng(0)
X_test = X[split:].copy()
n_test = len(X_test)
inject_idx = rng.choice(n_test, size=n_test//20, replace=False)
X_test[inject_idx] += rng.normal(4, 1, size=(len(inject_idx), X.shape[1]))

scores = -iso.score_samples(X_test)
threshold = np.quantile(-iso.score_samples(X[:split]), 0.9)
pred_anom = scores > threshold
true_anom = np.zeros(n_test, bool); true_anom[inject_idx] = True
p, r, f, _ = precision_recall_fscore_support(true_anom, pred_anom, average="binary")
print(f"\nSynthetic injection — Precision={p:.2f} Recall={r:.2f} F1={f:.2f}")

# (c) Sanity plot
import matplotlib.pyplot as plt
stress_series.resample("1D").mean().plot(figsize=(10,3),
    title="Ocean Stress Index over CCE2-17 deployment")
plt.axhline(1.0, color="k", ls="--", alpha=0.5); plt.show()

# ============================================================
# CELL 6 — Wire into OceanScore
# ============================================================
IMPACTS = {
  "beef":     {"co2":99.5,"runoff":0.95,"plastic":0.3,"water":15400},
  "poultry":  {"co2":9.9, "runoff":0.55,"plastic":0.4,"water":4300},
  "legume":   {"co2":0.9, "runoff":0.15,"plastic":0.2,"water":4055},
  "vegetable":{"co2":2.0, "runoff":0.25,"plastic":0.4,"water":322},
  "fish":     {"co2":13.6,"runoff":0.25,"plastic":0.6,"water":3700},
  "dairy":    {"co2":9.8, "runoff":0.80,"plastic":0.5,"water":1020},
  "fruit":    {"co2":1.1, "runoff":0.20,"plastic":0.4,"water":962},
  "processed":{"co2":5.0, "runoff":0.40,"plastic":0.8,"water":2000},
}
WORST = {"co2":30, "runoff":0.6, "plastic":0.6, "water":5000}

def ocean_score(category, stress_idx=current_stress):
    f = IMPACTS.get(category, IMPACTS["vegetable"])
    co2     = 1 - min(f["co2"]/WORST["co2"], 1)
    runoff  = 1 - min((f["runoff"]*stress_idx)/(WORST["runoff"]*1.5), 1)
    plastic = 1 - f["plastic"]
    water   = 1 - min(f["water"]/WORST["water"], 1)
    return round(100*(0.35*co2 + 0.30*runoff + 0.20*plastic + 0.15*water))

import requests

HEADERS = {"User-Agent": "OceanScore/0.1 (datahacks2026)"}

def barcode_to_score(barcode):
    url = f"https://world.openfoodfacts.org/api/v2/product/{barcode}.json"
    r = requests.get(url, headers=HEADERS, timeout=10)
    if r.status_code != 200:
        return {"error": f"HTTP {r.status_code}"}
    try:
        data = r.json()
    except ValueError:
        return {"error": "non-JSON response", "body": r.text[:200]}
    if data.get("status") != 1:
        return {"error": "product not found", "barcode": barcode}
    p = data["product"]
    cats = p.get("categories_tags") or []
    cat_map = {
        "beef":"beef", "chicken":"poultry", "poultry":"poultry",
        "fish":"fish", "seafood":"fish", "dairy":"dairy",
        "legumes":"legume", "vegetables":"vegetable", "fruits":"fruit",
        "chocolate":"processed", "spreads":"processed",
        "sugary-snacks":"processed", "snacks":"processed",
        "sodas":"processed", "beverages":"processed",
    }
    category = next((v for k,v in cat_map.items() if any(k in c for c in cats)), "processed")
    return {"name": p.get("product_name"), "category": category,
            "score": ocean_score(category), "stress_idx": current_stress}

print(barcode_to_score("3017620422003"))  # Nutella

# ============================================================
# CELL 7 — Validate OceanScore against OpenFoodFacts Eco-Score
# ============================================================
import requests, time
from scipy.stats import spearmanr
import pandas as pd

# 50 real barcodes across categories — meat, dairy, processed, produce, etc.
BARCODES = [
    "3017620422003",  # Nutella
    "5449000000996",  # Coca-Cola
    "8076809513753",  # Barilla pasta
    "3175680011480",  # canned green beans
    "0028400090315",  # Doritos
    "0038000138416",  # Cheerios
    "7622210449283",  # Oreo
    "3046920022606",  # Lindt chocolate
    "4006381333641",  # Stabilo (won't have ecoscore — filtered)
    "8000500310427",  # Ferrero Rocher
    "3033710065967",  # President butter
    "3608580736912",  # Yoplait yogurt
    "3270190022114",  # Evian water
    "3245412567216",  # bread
    "3560070048786",  # Carrefour rice
    "8001505005707",  # San Pellegrino
    "5000159407236",  # Snickers
    "3329770063648",  # apples
    "20724696",       # bananas
    "3068320115008",  # Volvic
    "3033491510014",  # baguette
    "3257980031000",  # tuna can
    "3270160830053",  # cornflakes
    "8480000823779",  # olive oil
    "5000168190631",  # tea bags
    "3661112004143",  # ground beef
    "8410076472199",  # chickpeas
    "3038359005114",  # lentils
    "3168930010265",  # camembert
    "3023290260166",  # ham
    "5411188119098",  # Belgian beer
    "8000430112856",  # Mulino Bianco
    "5057967388912",  # Tesco milk
    "3245391225114",  # Carrefour eggs
    "8410128710262",  # Iberico ham
    "3700214612385",  # frozen pizza
    "3596710443307",  # frozen peas
    "3175681810044",  # canned tomatoes
    "8002270014901",  # Lavazza coffee
    "3023470001015",  # Roquefort
    "3033491610011",  # croissant
    "3560070976478",  # orange juice
    "3017800238400",  # Bonduelle corn
    "3242272379354",  # apple juice
    "8717377001135",  # Heinz ketchup
    "5410188006438",  # Alpro soy milk
    "3596710401352",  # frozen salmon
    "8000380025114",  # Mutti tomato sauce
    "3017620425035",  # Kinder Bueno
    "3245412365119",  # baguette
]

HEADERS = {"User-Agent": "OceanScore/0.1 (datahacks2026)"}

def fetch_product(barcode):
    try:
        r = requests.get(
            f"https://world.openfoodfacts.org/api/v2/product/{barcode}.json",
            headers=HEADERS, timeout=10
        )
        if r.status_code != 200: return None
        d = r.json()
        if d.get("status") != 1: return None
        p = d["product"]
        eco = p.get("ecoscore_score")
        if eco is None: return None  # skip products without an ecoscore
        cats = p.get("categories_tags") or []
        cat_map = {
            "beef":"beef", "chicken":"poultry", "poultry":"poultry",
            "fish":"fish", "seafood":"fish", "dairy":"dairy",
            "legumes":"legume", "vegetables":"vegetable", "fruits":"fruit",
            "chocolate":"processed", "spreads":"processed",
            "sugary-snacks":"processed", "snacks":"processed",
            "sodas":"processed", "beverages":"processed",
        }
        category = next((v for k,v in cat_map.items() if any(k in c for c in cats)), "processed")
        return {
            "barcode": barcode,
            "name": p.get("product_name","")[:30],
            "category": category,
            "ecoscore": eco,
            "oceanscore": ocean_score(category),
        }
    except Exception as e:
        return None

rows = []
for b in BARCODES:
    row = fetch_product(b)
    if row: rows.append(row)
    time.sleep(0.1)  # be nice to the API

results = pd.DataFrame(rows)
print(f"Got {len(results)} products with both scores\n")
print(results.to_string(index=False))

rho, pval = spearmanr(results["ecoscore"], results["oceanscore"])
print(f"\nSpearman ρ = {rho:.3f}   (p = {pval:.4f})")
print("Interpretation: >0.6 = good, 0.3–0.6 = okay, <0.3 = weights are wrong")