import Foundation

// AUTO-GENERATED by ml/env_regression/train.py. Do not edit by hand — rerun
// the trainer to update coefficients after editing agribalyse_curated.csv.
//
// Predicts (co2_kg, runoff_intensity, plastic_intensity, water_l_per_kg) for a
// grocery item from (category one-hot, log size_kg). Trained on a curated
// Agribalyse-derived dataset; see ml/env_regression/agribalyse_curated.csv.
enum EnvRegressionModel {

    struct Prediction {
        var co2Kg: Double           // kg CO2-eq per kg product
        var runoffIntensity: Double // 0..1, higher = more fertilizer runoff
        var plasticIntensity: Double// 0..1, higher = more plastic burden
        var waterLPerKg: Double     // liters per kg product
    }

    static let categories: [String] = [
        "beef",
        "dairy",
        "poultry",
        "seafood",
        "vegetables",
        "fruit",
        "legumes",
        "grains",
        "packaged snacks",
        "beverages",
        "household",
        "unknown",
    ]

    static func categoryIndex(_ category: FoodCategory) -> Int {
        switch category.rawValue {
        case "beef": return 0
        case "dairy": return 1
        case "poultry": return 2
        case "seafood": return 3
        case "vegetables": return 4
        case "fruit": return 5
        case "legumes": return 6
        case "grains": return 7
        case "packaged snacks": return 8
        case "beverages": return 9
        case "household": return 10
        case "unknown": return 11
        default: return 11
        }
    }

    // co2_kg  R²=0.999  MAE=0.132
    static let co2_kgCoef: [Double] = [
        4.447188486, 23.2423901, -0.7480761003, 2.663431516, 2.102235921, -3.534706226,
        -3.376567276, -3.262602998, -2.813001537, -2.202992815, -3.773223906, -1.645891453,
        -2.203806641, 0.3566202152
    ]

    // runoff_intensity  R²=0.998  MAE=0.007
    static let runoff_intensityCoef: [Double] = [
        0.4388755951, 0.468964648, 0.3154180678, 0.1335835958, -0.1717328135, -0.07781007829,
        -0.1284163518, -0.2038142994, -0.03251715244, 0.1144445085, -0.1981017361, 0.1843979597,
        0.0344592419, 0.04013876007
    ]

    // plastic_intensity  R²=0.995  MAE=0.011
    static let plastic_intensityCoef: [Double] = [
        0.4348676284, -0.1868200343, -0.008592139169, -0.02216414669, 0.1801130178, -0.2552062617,
        -0.1621641187, -0.2570652511, -0.1862977804, 0.3880564577, 0.410301168, 0.4459521609,
        0.08875456315, 0.04046064229
    ]

    // water_l_per_kg  R²=1.000  MAE=53.438
    static let water_l_per_kgCoef: [Double] = [
        2900.639537, 12693.8351, -1716.973976, 1480.724842, 970.9420639, -2458.630772,
        -1830.874496, 1270.519756, -1198.267857, -1134.254801, -2262.230361, -1602.029757,
        -1312.120218, 146.754918
    ]

    // Dataset-median of log(water_l_per_kg). Used by OceanScoreEngine to
    // recenter the water normalization so typical products land mid-scale.
    static let waterMedianLog: Double = 7.229838778
    // Reference size (kg): scanned products this size get size_scale = 1.
    static let referenceSizeKg: Double = 0.5
    static let trainingRows: Int = 65

    // Build [bias, cat one-hot..., log(size_kg)] feature vector.
    private static func features(for category: FoodCategory, sizeKg: Double) -> [Double] {
        var vec = [Double](repeating: 0.0, count: 2 + categories.count)
        vec[0] = 1.0
        let idx = categoryIndex(category)
        vec[1 + idx] = 1.0
        vec[vec.count - 1] = log(max(sizeKg, 1e-3))
        return vec
    }

    private static func dot(_ a: [Double], _ b: [Double]) -> Double {
        var sum = 0.0
        for i in 0..<a.count { sum += a[i] * b[i] }
        return sum
    }

    static func predict(category: FoodCategory, sizeKg: Double) -> Prediction {
        let x = features(for: category, sizeKg: sizeKg)
        return Prediction(
            co2Kg:            max(0.0, dot(x, co2_kgCoef)),
            runoffIntensity:  min(1.0, max(0.0, dot(x, runoff_intensityCoef))),
            plasticIntensity: min(1.0, max(0.0, dot(x, plastic_intensityCoef))),
            waterLPerKg:      max(0.0, dot(x, water_l_per_kgCoef))
        )
    }
}
